###################################################
# Services
#
# The services define the individual components of our application stack.
# For each service, a separate container will be launched.
###################################################
services:
  ###################################################
  # Service: client
  #
  # The client service is the React app that provides the frontend for the app.
  # When the container starts, it will use the image that results from building
  # the Dockerfile, targeting the dev stage.
  #
  # The Compose Watch configuration is used to automatically sync the code from
  # the host machine to the container. This allows the client to be automatically
  # reloaded when code changes are made.
  # 
  ###################################################
  client:
    build:
      context: ./
      target: client-dev
    volumes:
      # Below line will sync changes from queue folder to container and vice versa used for hot reloading
      - ./client:/usr/local/app
      # Below line Prevents node_modules to sync to host machine but we can install the packages from inside the docker container and doing that will just simply update the package.json and package-lock.json files on host machine keeping things cleaner 
      - node_modules:/usr/local/app/node_modules
    ports:
      - 5173:5173


  



volumes:
  node_modules: